### ISSUE TITLE
Warriors of Might and Magic (gbc) - corrupted status bar

### ISSUE THREAD

**Issue by ghost** [LIJI32/SameBoy#123]
Looks like same one as this and fixed by endrift. Just start new game and see strange tiles at bottom. Latest svn and tried some mid-2017 builds too.
https://github.com/mgba-emu/mgba/issues/409

Video of gameplay
https://www.youtube.com/watch?v=QWMiYRnoXOY

**Comment by LIJI32** [comment]
Window rendering is still inaccurate in 0.11, as researching the window would have delayed 0.11 for quite a bit. This is planned for 0.12. :)

**Comment by Sanaki** [comment]
Confirmed this issue is still valid in 0.13.6 74acc93 libretro build.
SameBoy status bar:
![Warriors of Might and Magic (USA) (En,Fr,De)-201118-155856](https://user-images.githubusercontent.com/1374333/99602883-2983d300-29fa-11eb-9e4d-efcefafe82c6.png)

The same shot from mGBA:
![Warriors of Might and Magic (USA) (En,Fr,De)-201118-155919](https://user-images.githubusercontent.com/1374333/99602904-36082b80-29fa-11eb-8767-cc9c1da9899d.png)

**Comment by LIJI32** [comment]
Funny, looks like this game isn't using the window at all! Seems interesting.

**Comment by LIJI32** [comment]
Ok, this game is "doing the stupid". It doesn't actually use the window at all, but it still enables and disable the window mid frame. However, when it does enable the window, it uses WX=0, which is an invalid value for an active value according to Nintendo. What actually happens when WX=0 is correctly emulated on the DMG, but not on the CGB (Where it seems to make the window disabled).
