### ISSUE TITLE
Remove -Werror from default CFLAGS

### ISSUE THREAD

**Issue by AntonioND** [LIJI32/SameBoy#166]
I understand that the idea is to force the code to always be warning-free, but it isn't realistic to expect new versions of the compiler to always work as they might detect new problems and add new warnings.

**Comment by AntonioND** [comment]
Oh, I see there was a similar issue: https://github.com/LIJI32/SameBoy/pull/119

In any case, I disagree with the reply. It is unrealistic to expect to always be warning-free.

**Comment by LIJI32** [comment]
My personal experience shows that codebases where builds can pass with warnings eventually ends up piling compiler warnings. Compilers (GCC and Clang) generally introduce new warnings in major version, which are released once a year, so that's at most twice a year the build can break. If breaking the build twice a years, in the absolutely worst case, is the price I have to pay for generally improved code quality, I'm fine with that. Specifically for my and SameBoy's case, it's also useful for platform specific problems that can be detected via compiler warnings, as I don't regularly test Windows and Linux builds – build breaks are likely to be reported sooner than plain warnings.

That said – the `-Werror` practice comes from my personal experience as a developer of security-critical, commercial closed source software, in companies where compiler upgrades are much more managed. If actual specific problems arise from the use of `-Werror`, I'm always happy to address those ASAP.

**Comment by AntonioND** [comment]
Yeah, sure, removing warnings is great, but you can leave ``-Werror`` enabled during development and in the CI tests, and force all new patches to the codebase to fix all warnings. That way you don't introduce new ones to the codebase, but let any user compile it even if their specific compiler generates more warnings. This is specially annoying for distribution packagers, as the process can't be automated and they may need to patch your code for it to build.

As a matter of fact, all warning flags should be optional during builds. I see no reason why this project shouldn't build with GCC, but all the warning flags would prevent that from happening. Maybe you could have release/verbose builds, and make it always default to verbose or something similar.

**Comment by LIJI32** [comment]
There are actually several more problems:

1. The default build configuration is debug (No optimizations, symbols kept). This should probably be reconsidered.
2. Tagged revisions (releases) should always compile on both GCC and Clang. Maintainers should *never* use untagged revisions as they're considered unstable and may have compatibility issues with tagged versions.

Perhaps a specific build configuration for maintainers should be added where it ignores warnings, but the downside of it that these warnings will probably not be reported.
