### ISSUE TITLE
Regression? SameSuite/apu/div_write_trigger_10.gb fails

### ISSUE THREAD

**Issue by NieDzejkob** [LIJI32/SameBoy#228]
(checking on SameBoy commit `38ee0206532a7cc48ad707082b1265bfc0547cd6`, current master AFAICS)

**Comment by LIJI32** [comment]
Turns out I somehow missed my own test. So basically two APU quirks conflicted:
```
/* APU glitch: When turning the APU on while DIV's bit 4 (or 5 in double speed mode) is on,
       the first DIV/APU event is skipped. */
```
and 
```
/* APU glitch - if length is enabled while the DIV-divider's LSB is 1, tick the length once. */
 ```
Turns out that when the first glitch occurs, the APU sequencer (referred to as DIV-divider in the source) starts with 1 instead of 0. After the first non-skipped DIV-APU event, the APU sequencer still doesn't advance to 2, it happens only after the second event. Since it affects the sequencer's LSB, it triggers the second quirk. I bet there's a more sensible way to model this, but it works and it's accurate.

Illustration:
```
Value of the APU Sequencer:
Usual Case (First quirk not triggered):  0  1  2 3...
Odd Case (First quirk triggered):        1 (1) 1 2 3...
Odd Case (Before this fix):              0 (0) 1 2 3...

() denotes a skipped event
The first value denotes the initial value of the sequencer, not an actual APU-DIV event.
```
