### ISSUE TITLE
Windows Defender detected trojan in v0.13.6 release build

### ISSUE THREAD

**Issue by iliana** [LIJI32/SameBoy#287]
https://www.virustotal.com/gui/file/c6c1f914c4e6fbfb0aa95f437f832be4b97eb5a14f036471310db36496046f7f/details

![image](https://user-images.githubusercontent.com/52814/92517976-7bbfa100-f1cc-11ea-825a-f51c112e1b05.png)

I don't have the research chops to dig in and see if the executables actually have trojans in them, but you might want to [submit the builds for analysis](https://www.microsoft.com/en-us/wdsi/filesubmission/), as apparently this particular detection has a high false-positive rate among other projects on GitHub.

**Comment by lotharsm** [comment]
Ah, I had this problem too a couple of days ago. Can you please check if your Defender signature definitions are up-to-date? I can't reproduce this issue anymore on my machine.

**Comment by iliana** [comment]
They're up to date. I went ahead and submitted the file to Microsoft to take a look. I'll update here when I get an email back.

**Comment by LIJI32** [comment]
I submitted the binaries to analysis; but passing the trade-secret, ever-changing, arbitrary heuristics of several dozens of anti-viruses, most of them having a false positive rate high enough to consider them a malware of their own, is not a goal; especially when it has to be done for every version I release. (See my tweet about how terrible these solutions are and why they shouldn't be trusted anyway: https://twitter.com/liji32/status/1294648985710403584)

I'm keep this issue open for further discussion and updates though.

**Comment by iliana** [comment]
Yep, agreed wholeheartedly :) Wanted to open an issue just to make sure it's here for anyone else seeing the same issue.

**Comment by LIJI32** [comment]
Both Microsoft and McAfee whitelisted SameBoy by now, although some antivirus software already copied their detection for 0.13.6 by reputation. 0.13.6b, which is identical other than a single byte change, is currently only detected by an obscure antivirus called SecureAge APEX, which I nickname RTEE – Return True Enterprise Edition, because it returns "Malicious" for *every single binary compiled with clang*, as well as many other binaries compiled with various versions of MSVC. I sent VirusTotal a request to remove SecureAge APEX from their service due to the harmfully high level of false positives.
