### ISSUE TITLE
[Feature] Make "ld b,b" debugger breakpoint

### ISSUE THREAD

**Issue by jkotlinski** [LIJI32/SameBoy#359]
What it says :)

**Comment by LIJI32** [comment]
This feature already exists, you need to enable it using the `softbreak` debugger command.

**Comment by jkotlinski** [comment]
Could you advise if there some way to enable it automatically on startup?
Or if there is a way to pass in debugger commands through command line, to
be executed before program start? Typically I start SameBoy by pressing
function key in my favorite text editor. So looking then for a way not to
type this command manually every time.

**Comment by NieDzejkob** [comment]
You could launch SameBoy with `cat <(echo softbreak) - | sameboy foo.gb`.

**Comment by LIJI32** [comment]
It's tricky having it enabled on start because it requires cooperation from every frontend. SameBoy is not always running with anything commanding its debugger; the Cocoa frontend can have its debugger completely disabled and enabled by user request and the libretro frontend doesn't have debugging capabilities at all. If `ld b,b` is to be encountered in Cocoa with debugging disabled, the user would have to enable debugging, open the console, and enter `c` to continue. In the libretro frontend, it would simply freeze the core. Even in the SDL frontend, if you run it without `stdin` (which implicitly inputs a `c` when attempting to read from EOF), you could effectively freeze SameBoy to death by running `ld b,b` in a busy loop, making the frontend perform system calls at an absurdly high rate.

**Comment by jkotlinski** [comment]
Right... from the looks of it, I guess nothing should be changed in the
core.
But perhaps SDL sameboy debugger build could be enabled so that this by
default enabled, as a convenience.
I understand that this is a low prio thing though.
