### ISSUE TITLE
BootROM adaptation for own emulator allowed?

### ISSUE THREAD

**Issue by ArcticXWolf** [LIJI32/SameBoy#415]
Heyho,

currently I am searching for an opensource bootrom for CGB and DMG for my own [emulator ](https://github.com/ArcticXWolf/AXWGameboy) because I do not want to use the original ones (for copyright reasons obv.), but also want to enable palette selection during boot.
I found your bootroms here and wanted to ask, if I am allowed to 1. integrate them into my emulator (and also add them into my repo) and 2. change the integrated Logo to something else.

Finally my last question is: How was the logo.png created? I tried to modify the existing one, but afterwards the graphics in the bootrom were scrambled. Maybe an encoding issue? Can you tell me with which tools/settings were the PNG created?

Greetings,
ArcticXWolf

**Comment by LIJI32** [comment]
1. As long as the MIT license is followed (Append the copyright notice and the license iteself to the boot ROMs in both source and binary distributions), you can use them.
2. Two tiles are shared between the letters E and B. The boot ROM takes advantage of it to better compress the logo since it's very tight on space. You will need to modify the boot ROM if you change the logo.

**Comment by ArcticXWolf** [comment]
Just for your information:
I've added the bootrom now to my emulator with the LICENSE file and links to your project on the main README and a special README in the bootroms. [Direct link](https://github.com/ArcticXWolf/AXWGameboy/tree/master/internal/bootroms)

My logo has just changed the beginning of the logo because the repeating patterns in your bootroms were to hard for me to change, hope thats fine for you.

If something isnt to your liking or does not fulfill the license requirements, feel free to answer here and I will adjust ASAP.

Thanks for all your work!
