### ISSUE TITLE
Possibility of adding Windows under Buildability and Sanity?

### ISSUE THREAD

**Issue by RokkumanX** [LIJI32/SameBoy#424]
Seems to me that downloading the latest "nightly" whether it be for MacOS or Ubuntu is possible under the Buildability and Sanity area but not Windows, is there a particular reason for it to be so?

Would it be possible to add Windows builds also without to much hassle?

Thanks in advance!

**Comment by LIJI32** [comment]
SameBoy's build environment requirement on Windows include several tools that are not preinstalled in the GitHub Actions image, and are not trivial to install from a script due to Windows general GUI driven nature. Additionally "nightly" builds often contain regressions and often break save state compatibility, so they should be used with caution.

**Comment by RokkumanX** [comment]
Thanks for the info, I'll continue to build and use the Libretro core in the mean time then.
