### ISSUE TITLE
Distorted audio in latest builds

### ISSUE THREAD

**Issue by RokkumanX** [LIJI32/SameBoy#426]
Hi

I updated my repository with the latest changes and built the Libretro core this morning and found out many games had distorted audio and I believe Shantae sounded worst of them all (this was my own built core with commits all up to https://github.com/LIJI32/SameBoy/commit/8e675295a82c1861cc89aca62c2ba7380a33634b)

Thankfully I have plenty of core backups and going back to the 5th of December (this commit https://github.com/LIJI32/SameBoy/commit/9e57201b0820ece8b1087579422347f2f776e3a6) things sounds fine.

Also I would like to add that using the real agb_boot.bin (NOT the one that ships with SameBoy) the sound is a bit worse, is the real agb_boot.bin properly supported?
At least when I used this BIOS in the latest build the sound was very bad for Zelda Oracle of Ages and Oracle of Seasons but sounded better with the 5th of December one.

File hashes:
SHA256: fe3cceb79930c4cb6c6f62f742c2562fd4c96b827584ef8ea89d49b387bd6860
SHA1: fa5287e24b0fa533b3b5ef2b28a81245346c1a0f
MD5: e6cefb5f7d352fab6681989763917c73

As a side note, Gearboy works great with this BIOS. I don't think SameBoy doesn't support it but the one that ships with SameBoy that you have made didn't have as bad sound distortions as the real one.

I'll try to assist you in helping you with this issue in any way I can but likely something have broken since 5th of December up to 30th of December.

**Comment by LIJI32** [comment]
The boot ROM differences are coincidental, they have zero effect on audio. I suspect that 769aac9 is the relevant commit. Can you compare 769aac9 and db50462 and see if there's any difference?

**Comment by RokkumanX** [comment]
Thanks for your feedback!

I downloaded the source for both https://github.com/LIJI32/SameBoy/commit/769aac93c04d4bc8a395170c64d2c69e2998f6c8 and https://github.com/LIJI32/SameBoy/commit/db50462710d59ce215b4dbe152221a275f296d21 from this repository but I can't seem to build it with MSYS2 like I can with the updated source from my forked Libretro repository.

Whenever I try to build directly from your source it throws errors about bootroms.

I can't seem to get around it, but if I build from my repository https://github.com/RokkumanX/SameBoy it builds just fine.

What to do???

**Comment by Ryunam** [comment]
I have performed a few tests and recorded the audio output produced by the libretro core as of the aforementioned commits.

However, at least when I compiled the core with the self-built BootROMs present in the libretro downstream repository, I am not noticing any discernible difference or distortion in the audio.

1) This is with the latest core downloaded through the libretro buildbot (latest commit obtained from upstream on this version is f3277ab8d32e966198923be6cdbcac7301b4115c):

https://user-images.githubusercontent.com/17614150/148688234-66d8d1d4-4a86-4cd1-b407-fc0028ee9a04.mp4

2) This is the core compiled from https://github.com/RokkumanX/SameBoy, but reset to commit 769aac93c04d4bc8a395170c64d2c69e2998f6c8:

https://user-images.githubusercontent.com/17614150/148688277-415a84d0-0c64-45e4-92d2-885d705c5e96.mp4

3) This is the core compiled from https://github.com/RokkumanX/SameBoy, but reset to commit db50462710d59ce215b4dbe152221a275f296d21:

https://user-images.githubusercontent.com/17614150/148688295-0c75f3ce-6491-445f-9fc1-b0960487c59f.mp4

@RokkumanX Can you make a recording of how it sounds on your end? Also, in order to build those two commits above, what you need to do is copy over from the downstream libretro repository both the BootROMs/prebuilt folder and the Makefile located inside the libretro folder. Once you do that, you should be able to compile those two commits without any issue.

**Comment by RokkumanX** [comment]
I'm sorry for not replying sooner @Ryunam but I have recently begun a new job and have been very busy with very little time over for gaming and testing.

This will have to wait a little bit longer until I got more time later on but I'll keep this open in the mean time.

**Comment by Ryunam** [comment]
Hi @RokkumanX, did you figure this out ultimately? If that’s the case, knowing that you’re currently busy with work, I can take care of pulling the latest changes to the Libretro downstream repo. Let me know!

**Comment by RokkumanX** [comment]
@Ryunam 

Unfortunately no, I haven't touched this for months and the only thing I actually do is to update my fork with the latest changes from this repository.

No builds, no testing, nothing to show. I don't really know why I keep doing it, maybe my hope is to come back at some point but with all things going on I just can't find myself relaxing with games anytime soon.

If you want to continue where I left off I would be more than delighted, I have kinda given up.
