### ISSUE TITLE
GBC: Missing emulation of LCD protection circuit

### ISSUE THREAD

**Issue by jdrockerduck** [LIJI32/SameBoy#432]
At least that is my assumption.
The game FIFA 2000 (USA, Europe) (SGB Enhanced) repeatedly turns the lcd on and off. On my GBC this does not lead to flickering but it does on SameBoy. My assumption is that the lcd proteciton circuit keeps the last frame on screen for a while before going white.
Tested with sameboy_winsdl_v0.14.2. This happens at the beginning during the EA logo as well as during the stadium rotating.

https://user-images.githubusercontent.com/61698140/150646838-c27cb5a0-9866-4503-9c02-4c0bac88e4fc.mp4

**Comment by OFFTKP** [comment]
Also getting flickering on my machine

**Comment by OFFTKP** [comment]
Could this be related? From pan docs:

> On SGB, the screen doesn’t turn white, it appears that the previous picture sticks to the screen. (TODO: research this more.)

[Source](https://gbdev.io/pandocs/LCDC.html#lcdc7---lcd-enable)

**Comment by CasualPokePlayer** [comment]
"LCD protection circuit" isn't really the right term here. The quirk is more the GB/C will "stick" the current image to the screen for a frame, due to the lack of a vsync signal. The next frame will then white out. SameBoy does emulate this, although I guess the timing isn't correct someplace causing the white out to occur here anyways.
