### ISSUE TITLE
Libretro port runloop issues

### ISSUE THREAD

**Issue by twinaphex** [LIJI32/SameBoy#5]
Hi there,

@not6 did most of the work so far on doing a basic libretro port. We have made some nice progress.

Our only problem so far though is that the runloop that has to be implemented doesn't really fit our model.

It would be best if we could run exactly one frame once every retro_run call, without needing to have a vblank handler active.

Because the runloop is not implemented right now in a way libretro understands, fastforwarding and rewinding is currently not possible.

You can see what we currently do for SameBoy here -

https://github.com/libretro/SameBoy/blob/master/libretro/libretro.c#L272

This is our vblank callback implementation -

https://github.com/libretro/SameBoy/blob/master/libretro/libretro.c#L142

You can see here how we implemented the runloop for another GBC/GB emulator, Gambatte - 

https://github.com/libretro/gambatte-libretro/blob/master/libgambatte/libretro/libretro.cpp#L829

Thanks for the great work on this emulator.

**Comment by LIJI32** [comment]
Sure, I can add an API for that; just a few questions:
1. I assume this means libretro expects emulator to not handle any FPS capping, so nanosleep should not be called when this API runs, am I right?
2. The vblank interval is not always constant on the Game Boy, due to being able to turn the screen on and off. Assuming it is constant will causes noticeable sound pops and jumps in some games (Pokémon Pinball for example). How would libretro handle that? Should the actual time passed be returned?
3. Any special requests for sounds? Ability to control the buffer size directly?

I'll be going on a ~2 week vacation tomorrow morning and I won't be able to work on SameBoy during that time, hopefully if you answer quick enough I'll be able to commit tonight. :)

**Comment by twinaphex** [comment]
Hi there,

1. FPS capping is not needed for a libretro port, what we do is we set the audio rate and the refresh rate on the libretro core side and then the FPS capping is done by the frontend itself. So the core should stay mostly out of the way of such things. So nanosleeping and the like is all unnecessary and is best left avoided.
2. Not sure about this or how Gambatte deals with it.
3. No special requests really. The best way would be is if we dont' have to set a sound callback and we can just grab a 16-bit sound buffer for each retro_run iteration with a 'size' variable and then just pass that off to the audio_batch_cb callback for audio output.

Have a good vacation!

**Comment by LIJI32** [comment]
1. Assumed so, no problem. I'll add the API in a few minutes.
2. I guess this can be left unhandled for now and fixed later, but the libretro port should have a separate issue for that. How does libretro handle consoles with non-constant FPS? I assume it's more common and critical on more modern consoles.
3. Good, since SameBoy doesn't have an audio callback. The API you need is GB_apu_copy_buffer. Note that it will pad the output with zeros if not enough samples were generated. Also note that the GB's usual FPS is not 60, but about 59.72 (16742706 nanoseconds per frame, or 70224 CPU clocks on 0x400000 Hz CPU frequency). Using 60 as the usual FPS will cause noticeable sound pops.

**Comment by twinaphex** [comment]
Thank you for adding this. I will look into implementing this tomorrow.

**Comment by aliaspider** [comment]
about the non constant fps in gameboy cores, it is handled simply by keeping track of audio samples, and duplicating a frame if `frame_count < audio_samples / 35112`, that way constant 60fps output can be maintained from the core.
another approach is to just present the last completed frame every 35112 audio samples.

**Comment by LIJI32** [comment]
Makes sense, although I think the current sound API won't support it. Would an API returning the number of available samples in the buffer be enough?

**Comment by aliaspider** [comment]
yes
