### ISSUE TITLE
Switch Joy-Con support?

### ISSUE THREAD

**Issue by qxrv** [LIJI32/SameBoy#507]
I didn't know this until recently but apparently I can just pair my Nintendo Switch Joy-Cons via bluetooth with my MacBook (I was under the assumption that only Switch Pro controllers were supported). However, when both Joy-Cons are connected, I can't seem to map anything; when either one (L or R) is connected, I'm able to map the controls to whatever button-press I want from that particular Joy-Con, but obviously, just one of them won't do for proper gameplay. I've noticed the same problem with Ares as well. Somehow, mGBA and NanoBoyAdvance seem to pick up both Joy-Cons just fine, but I'd much rather play GB/GBC games on SameBoy as I have been for a while now cause of the accurate color corrections.

System: MacBook Air M1
macOS version: 12.6
SameBoy version: 0.15.6

**Comment by LIJI32** [comment]
The reason I don't support Joy-Cons at the moment (while I do support the Switch Pro Controller which is essentially identical protocol-wise) is because they can be used in odd combinations that would require both hacks inside the JoyKit framework I wrote for controllers, and in the UI/UX side to configure them. Supporting Joy-Cons strictly in a one-Joy-Con-per-player configuration and a single orientation is easy. But you can have complicated scenarios too: Imagine an 4-player SGB game, with 3 players currently playing; One player uses  2 Joy-Cons with a grip, and the remaining two use a single Joy-Con each, left and right. I would need a way to group one pair together, but only one of them, a way for the user to configure that pairing, adjust the inputs of the un-paired Joy-Cons if they're used in horizontal orientation, and finally allow the user to select a vertical orientation for single Joy-Cons.

With that said, I'll probably add basic Joy-Con support to 0.15.7, but I can't promise anything when it comes to the more advanced features mentioned above.

**Comment by qxrv** [comment]
Ah that makes a lot of sense; thanks for the explanation. I only need the single-player control scheme so I'm excited for the basic Joy-Cons support to drop :)
