### ISSUE TITLE
gbtests by _Judge don't pass

### ISSUE THREAD

**Issue by sczther** [LIJI32/SameBoy#51]
The test rom fails a few of the tests, using the latest libretro linux updater version.
I think I have the source code for it stuffed somewhere, let me know if it would be useful. It would also be good to verify the tests on real hardware, as they are quite old and some may be revision specific.

[gbtest.zip](https://github.com/LIJI32/SameBoy/files/1857873/gbtest.zip)

**Comment by LIJI32** [comment]
Does this ROM target the CGB or the DMG? Because it seems to check some PPU timings that are:

 * Known to be different between DMG and CGB
 * Could have changed between CGB-C and CGB-D

I'll compare the results with my CGB-E and SGB2 and see if they're any different, and in any case, sources are helpful. :)

**Comment by sczther** [comment]
I really have no idea or a way to check easily and from my talking to _Judge, he has no idea anymore too, this is like 10+ years old code for him. So better check yourself, or prod Gekkio with his battle arsenal :D

**Comment by LIJI32** [comment]
On my CGB-E the results are identical to SameBoy in CGB mode (which targets CGB-E), so that's nice. On my SGB2 (which should be equivalent to an MGB), however, the test fully passes, while SameBoy in DMG mode (which targets DMG-B) it fails pretty much exactly like my CGB. I'm not sure if this test passes on a DMG-B, but MGB/SGB2 should be closer to its real behavior, I guess that's a real problem I need to look into. :)

If you have the source anywhere, that would be VERY useful. :)

**Comment by sczther** [comment]
[gbtests_20070114.zip](https://github.com/LIJI32/SameBoy/files/1857927/gbtests_20070114.zip)
Look what I found :)

**Comment by LIJI32** [comment]
Awesome, thanks :D

**Comment by sczther** [comment]
This seems to pass on the latest master!

**Comment by LIJI32** [comment]
Oh nice! I think it's the `bit [hl]` regression that broke it, together with a few more tests, in the first place. Good to see it's working now. :)
