### ISSUE TITLE
Demo: Hot Gameboy by Icebird not Emulated correctly.

### ISSUE THREAD

**Issue by sttng** [LIJI32/SameBoy#516]
To be honest the demo looks botched also on original hardware DMG, but on sameboy_winsdl_v0.15.6 it looks botched differently and the music doesn't play until the end. 

https://www.pouet.net/prod.php?which=3803

**Comment by LIJI32** [comment]
Behaves just like on hardware on SameBoy 0.15.8, can you try with the latest version?

**Comment by sttng** [comment]
Just checked SameBoy 0.15.8 on macOS and it behaves different compared to my hardware. 
Transitions which are on hardware (in the video around 0:33) aren't done on SameBoy.
Also there is a "wobble" effect after the intro text (when the intro text scrolls down).
It is quite different on hardware, I think - even so definitely also botched on real HW.

https://user-images.githubusercontent.com/46765778/206891099-742e66ee-7bcc-4f1e-965d-10fec5c27d66.mp4

**Comment by LIJI32** [comment]
Oh I see it now, not sure what I did differently last time. I'll try figuring out what's going on with this ROM.

**Comment by LIJI32** [comment]
Aha, looks like the root cause of the difference is that the ROM reads and writes from MBC RAM despite not having any, triggering open bus behavior. This makes the ROM non-deterministic and also depend on various factor, including the flash cart used to test on hardware. I probably just had a "lucky" run last time I tried it on hardware and the cartridge returned just the right values (FF) which lead it to behave the same as SameBoy. I'm leaving this open as more accurate (although still deterministic) open bus behavior is still a goal.
