### ISSUE TITLE
Preferences don't open on compiled builds

### ISSUE THREAD

**Issue by Adamillo** [LIJI32/SameBoy#531]
For some reason the preferences window refuses to appear in the compiled version of Sameboy. The provided release binaries has working preferences

macOS version: 11.7.4
CPU: Intel i5-7360U
GPU: Intel Iris Plus Graphics 640
RAM: 8GB
Model of the iMac: iMac 21,5 inch 2017
Edit: Every compiled build has non working preferences

**Comment by LIJI32** [comment]
Can you share your compiled binary, as well as your build log (after running `make clean`)?

**Comment by Adamillo** [comment]
I can share the build, but I don't know how to show a build log

**Comment by Adamillo** [comment]
[SameBoy.app.zip](https://github.com/LIJI32/SameBoy/files/11172721/SameBoy.app.zip)

**Comment by Adamillo** [comment]
All it says after doing "make clean" is just "rm rf- build"

**Comment by LIJI32** [comment]
I meant running `make clean` then running `make` again and sharing the output.

**Comment by LIJI32** [comment]
It appears that by default, `ibtool` from Xcode 13.1 and newer will generate `nib` files that are not compatible with macOS Big Sur and older. Can you try modifying the Makefile to use `ibtool --target-device mac --minimum-deployment-target 10.9 --compile $@ $^ 2>&1 | cat -` rather than `ibtool --compile $@ $^ 2>&1 | cat -` and see if `make clean && make -sj` fixes this issue?

**Comment by Adamillo** [comment]
That change did indeed fix the issue!
