### ISSUE TITLE
[SDL] debugger reload command

### ISSUE THREAD

**Issue by titibandit** [LIJI32/SameBoy#537]
Using the text-based debugger, it would be practical to have a reload command in order to reload the ROM from there. It is already possible to do so by pressing escape on the gameplay window and reopening the ROM, but that's a bit impractical during a debugging session.
Cheers!

**Comment by LIJI32** [comment]
Reloading the ROM via the core (which is where the debugger lives) is actually very tricky because the location of the current ROM, battery saves, symbols, and so on are tracked and maintained by the frontend (SDL in this case) and the debugger is completely unaware of those. As a workaround, Ctrl+R in the gameplay window reloads the ROM and symbols.

**Comment by titibandit** [comment]
Thanks for the workaround and for the explanation.
It feels like this kind of things should be tracked by the core as well doesn't it?
Otherwise, could it be possible for the core just to send a "reload signal" to the frontend? I'm not sure how much refactoring would be involved in order to implement those things

**Comment by LIJI32** [comment]
Signaling the reload to the frontend seems to be a reasonable solution, thanks! I added the `reset` command which comes in 3 flavors:
`reset` – a normal reset, the ROM is not reloaded
`reset quick` A quick reset, the ROM is not reloaded, and values in RAM are preserved
`reset reload` A normal reset with ROM, symbol, and battery save reload

**Comment by titibandit** [comment]
Just tested it, seems to work great. Thanks!
