### ISSUE TITLE
IOS Rom Library

### ISSUE THREAD

**Issue by Joe-manji** [LIJI32/SameBoy#551]
When I try to open (or, more accurately, share) a ROM, it doesn't show up on the list of apps I can share it to. What should I do? Or is it a problem with the app?

**Comment by LIJI32** [comment]
Can you please list:
1. The iOS version you're using
2. The installation method you're using – sideloading the IPA file or installing the DEB file using a jailbreak
3. In case you're sideloading the app, are you installing it using AltStore or TrollStore?
4. In case you're installing the DEB file on a jailbroken device, which jailbreak are you using?

The reason I'm asking is that I have encountered similar issues when using jailbreaks with certain outdated tools before, but it could also affect other installation methods. SameBoy attempts to "fix" broken  installations of itself if it detects one, but I can't say it's bulletproof.

**Comment by Joe-manji** [comment]
1. iOS 16.1
2. Sideloading the IPA file
3. I used AltStore, and it launches, and everything seems fine, but I just can't load the ROMs.

Thanks!

**Comment by LIJI32** [comment]
It looks like this issue happens when the bundle identifier in the Info.plist file does not match the bundle identifier in `application-identifier` entitlement. When such case happens iOS not allow SameBoy to access files from the file sharing mechanism. Resigning SameBoy with matching Info.plist and entitlements will fix this. The next release will alert the user when such case happens and explain the issue.
