### ISSUE TITLE
 Cannot undo load state on the auto-loaded state (RetroArch/Libretro)

### ISSUE THREAD

**Issue by pressRtowin** [LIJI32/SameBoy#553]
Bit of a weird issue, and I'm not positive that this is a core issue and not a RetroArch issue, but so far SameBoy is the only affected core I've found. 

When using the option to automatically load the last state when opening content, attempting to undo that load results in an error message stating that no state was loaded to undo. This only happens with the initial auto load. Manually loading a state and undoing it works fine. And as stated before, among the 20 or so cores I use, I've only discovered this issue in SameBoy.

This was tested on multiple Android devices. Unfortunately, I have no access to a PC for the time being.

**Comment by LIJI32** [comment]
It really sounds like a RetroArch problem, a libretro core only really ever exports the functionality to load and save states and it's up to RA to make sensible use of them, but SameBoy being the only affected core sounds a bit weird. I'd open an issue in RetroArch's repo and see what they have to say, on the rare case it could be SameBoy misusing some libretro API, but I doubt it. I'm closing this for now, feel free to reopen it if it turns out to be a core issue.
