### ISSUE TITLE
Breakpoint not found

### ISSUE THREAD

**Issue by ISSOtm** [LIJI32/SameBoy#71]
Here's a paste from the command-line (I added ">" before my commands)
```
SameBoy v0.10.1
> break Reset.fadeLogo - 1
Breakpoint set at Reset+$00a ($00:$0167)
> delete $167
No breakpoint set at Reset+$00a ($0167)
> list
1 breakpoint(s) set:
 1. Reset+$00a ($00:$0167)
> del $00:$0167
Breakpoint removed from Reset+$00a ($00:$0167)
```
The problem is fairly self-describing: the first `del` command didn't succeed, and reported that the breakpoint didn't exist, when other commands did (including the second one)

I did not attach my ROM because I believe that's independent from the ROM.

**Comment by LIJI32** [comment]
This is by design, although it's not necessarily a very user-friendly design. The thing is that `$0167` and `$00:$0167` are two different breakpoints. The first one occurs whenever `pc == $0167`, and the second one occurs whenever `pc == $0167` AND the currently mapped bank at range `$0000-$4000` is 0 (Which is not necessarily true if the current MBC is MBC1, for example). The `del` command should probably be updated to allow less strict matching.

**Comment by ISSOtm** [comment]
I agree that the design is user-friendly (BGB uses the same, and I like it), but the response from `delete $167` is misleading, since it gives out the same label as all other commands (`Reset+$00a`). I think that should be changed rather than `delete`, which imo is fine as it is now.
