### ISSUE TITLE
Sound Quality [Windows (Libretro+SDL)]

### ISSUE THREAD

**Issue by Awakened0** [LIJI32/SameBoy#8]
The sound quality of both the Libretro and SDL ports of SameBoy on Windows seems bad when compared to Gambatte-Libretro. It's more noticeable on some games than others. The BIOS boot sound and the intro to Kirby's Block Ball had a pretty noticeable quality difference, so I did some recordings:

[KBB Gambatte-Sameboy Windows.zip](https://github.com/LIJI32/SameBoy/files/981324/KBB.Gambatte-Sameboy.Windows.zip)

The Gambatte clip is pretty clean, with just a few pops here and there. SameBoy Libretro and SDL sound like maybe they are playing at a lower KHz? More pops and clicks too.

**Comment by LIJI32** [comment]
The Windows port uses 44.1KHz sampling because, at least on my VM, it seems that SDL on Windows doesn't handle these frequencies well. The non-Windows ports, including Cocoa, use 96KHz. I believe the libretro port should be fine with 96KHz (it is currently 44.1).

I also plan adding pop prevention to the core itself which will significently improve quality in all ports.

I'll check the recordings attached when I'm home, they seem useful.

**Comment by Awakened0** [comment]
Sounds good, thanks!

**Comment by LIJI32** [comment]
It appears that the reason Gambatte sounds nicer is that it resamples the Game Boy's "native" frequency to its target frequency, which greatly improves the sound quality in lower sampling rates. I'll implement this in SameBoy as well.
