### ISSUE TITLE
Gensan 2 (J) missing speech

### ISSUE THREAD

**Issue by benderscruffy** [LIJI32/SameBoy#86]
at the start of the level and when you die is suppose to be speech  it is missing

**Comment by creambits** [comment]
Daiku no Gen-san - Robot Teikoku no Yabou (Japan) (GB)

Broke exactly here
https://github.com/LIJI32/SameBoy/commit/fc35111ae7bf23bb6ef8d854ee84aa80928bb45b

**Comment by creambits** [comment]
This change works but I have no idea if it's safe.

https://github.com/LIJI32/SameBoy/commit/fc35111ae7bf23bb6ef8d854ee84aa80928bb45b#diff-1b76aab5efef26f8309483f14860a160L36 becomes this
```
GB_sample_t output = {(0xf - value) * 2 * left_volume, (0xf - value) * 2 * right_volume};
```

because of that edit?
https://github.com/LIJI32/SameBoy/commit/fc35111ae7bf23bb6ef8d854ee84aa80928bb45b#diff-617e2cce9a9786931a0eb392b53e71e8L14

===================
===================


and this one
https://github.com/LIJI32/SameBoy/blob/master/Core/apu.h#L56
```
int8_t samples[GB_N_CHANNELS];
```

because of this?
https://github.com/LIJI32/SameBoy/commit/fc35111ae7bf23bb6ef8d854ee84aa80928bb45b#diff-1b76aab5efef26f8309483f14860a160L24
```
